### ISSUE TITLE
Flow-router vs react-router

### ISSUE THREAD

**Issue by ghost** [cult-of-coders/meteor-react-routing#1]
Not an issue indeed :)
Why choose flow-router against react-router as the package seems to be less and less followed by the developers? (of course this is a quick and unfair check based on the number of issues open and pulls from github) A general question is if we should keep flow-router for react-based project.

**Comment by theodorDiaconu** [comment]
@tetiogit I personally think it is much easier and it feels better than React-Router, JSX for defining routes seems like an odd way to do things. I like simple.
